# Generated by Django 2.1.7 on 2019-03-07 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('format', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
                ('result', models.BooleanField(default=False)),
                ('error', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Report')),
            ],
            managers=[
                ('passed_testcases', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('run_count', models.IntegerField()),
                ('last_run', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
                ('run_count', models.IntegerField()),
                ('last_run', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=None, to='app.Report')),
                ('testcase', models.ManyToManyField(to='app.Testcase')),
            ],
        ),
        migrations.AddField(
            model_name='testrun',
            name='testsuite',
            field=models.ManyToManyField(to='app.TestSuite'),
        ),
    ]
