# Generated by Django 2.1.7 on 2019-03-08 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190308_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='report',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='testcase',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='error',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='report',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='testsuite',
        ),
        migrations.AddField(
            model_name='testcase',
            name='testrun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.TestRun'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
    ]
