# Generated by Django 2.1.7 on 2019-03-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190309_0107'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testcase',
            managers=[
            ],
        ),
    ]
