# Generated by Django 2.1.7 on 2019-03-08 21:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190309_0309'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testcase',
            managers=[
                ('testcase', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='testrun',
            managers=[
                ('testrun', django.db.models.manager.Manager()),
            ],
        ),
    ]
