# Generated by Django 2.1.7 on 2019-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190309_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='failed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='passed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
