# Generated by Django 2.1.7 on 2019-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190310_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('result_1', models.BooleanField(default=False)),
                ('result_2', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
