# Generated by Django 2.1.7 on 2019-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190314_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(default='default', max_length=500),
        ),
    ]
